[package]
name = "rust-protobuf-compiler"
version = "1.0.0"
authors = ["Goodbye Kansas Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2021"

[dependencies]
# The version of prost-build is determined by tonic-build
prost-build = "*"
structopt = "0.3.26"
tonic-build = "0.10.2"

